### ISSUE TITLE
force push to a protected branch

### ISSUE THREAD

**Issue by allamand** [jklukas/git-push-fork-to-upstream-branch#5]
Hi,

the script makes a force push to a protected branch, but github reject this for me:

```
 ! [remote rejected] fork-to-test/fix_some_bug -> trigger-integration (protected branch hook declined)
```

Can you show how you configure your trigger-integration branch in github ?

thanks

**Comment by jklukas** [comment]
The default configuration for a repository should allow force pushing to a branch. What branch protection do you have configured? Perhaps you have a rule set up with a wildcard that protects all branches?

**Comment by allamand** [comment]
I configure "Require status checks to pass before merging" and I have only 2 rules one for master and one for trigger-integration. don't see other rules..

**Comment by allamand** [comment]
![image](https://user-images.githubusercontent.com/8956643/61302449-15b4d500-a7e6-11e9-8216-c15e84a7e171.png)

**Comment by jklukas** [comment]
I think you'd need to remove the protection rule for `trigger-integration`. This script relies on being able to replace the contents of that branch.

Are there specific situations you hope to prevent by having branch protection for `trigger-integration`?

**Comment by allamand** [comment]
In my comprehension I need to check "Require status checks to pass before merging" in order to specify which tests must be mandatory in order to the branch to be merged. You don't have marked the trigger-integration branch to be protecteed ?

**Comment by jklukas** [comment]
In my understanding, you generally want branch protection on for branches that have production significance. In simple cases, that's just `master`.

By having branch protection on for master, you ensure that nobody will be able to merge the contents of `trigger-integration` or any other branch into master without the necessary tests passing.

But `trigger-integration` exists only to accept code that tests will run on; nothing downstream depends on the contents of `trigger-integration`, so it should be "safe" for developers with write access to the repo to force push code there.

> You don't have marked the trigger-integration branch to be protected ?

No, generally, I only have branch protection rules configured for `master`, which is the branch used for deploying artifacts, etc.

**Comment by allamand** [comment]
@jklukas Thanks, I just misunderstand this configuration part in the CircleCI blog. Removing the branch protection solves the problem.
Thanks
